name: ${project.name}
description: ${project.description}
version: ${project.version}
author: zPedroo_
main: com.zpedroo.headholograms.Main
depend: [HolographicDisplays, WorldGuard]
commands:
  headhologram: